Autoset timebase:
  Max time of flight (us): 50
  Min time of flight (us): 42
  Horizontal scale (us): 5
Debugging:
  simulate_hw: true
  simulate_motors: true
  simulate_oscilloscope: true
  end_script_on_errors: false
Forward_Power_Meter:
  serial_number: '11408040323'
Reflected_Power_Meter:
  serial_number: '11506210019'
FrequencyParameters:
  HF:
    HF.Amplitude(mVpp): 50
    HF.BurstCount: 65
    HighFreqLimit(MHz): 13.8
    LowFreqLimit(MHz): 12.8
  LF:
    Amplitude(mVpp): 50
    BurstCount: 50
    HighFreqLimit(MHz): 4.8
    LowFreqLimit(MHz): 4
  Search:
    CoarseIncr(MHz): 0.1
    FineIncr(MHz): 0.01
Galil_Motors:
  axes:
  - X
  - R
  calibrate_ray:
  - 10000
  - 10000
  ip_address: 192.168.42.100
  jog_speed: 1
  reverse_ray:
  - false
  - false
  scan_speed: 1
Keysight_AWG:
  amplitude_V: 0.2
  burst: true
  burst_cycles: 4000
  burst_period_s: 0.1
  trig_in: false
  trig_out: true
  frequency_Hz: 4290000
  identifier: '0x2507'
  offset_V: 0
  output: true
  output_Impedance: 50
  set_on_startup: true
Keysight_Oscilloscope:
  channel: 1
  averages: 16
  capture_period_ns: 100
  cycles: 10
  delay_cycles: 0
  identifier: '0x179B'
  autorange_v_startup: False
  range_mV: 2000
  ext_trigger: False
  timeout_s: 20
  set_on_startup: True
MT_Balance:
  port: COM4
  timeout_s: .5
Paths:
  UA Serial numbers file: C:\Users\Isaiah\Documents\UA Serial Numbers\Serial
    numbers.txt
  UA results root directory: C:\Users\Isaiah\Documents\UA results
  Script log directory: C:\Users\Public\Documents\Results\Logs
Daq_Power_Relay:
  on_by_default: false
  port: COM3
  timeout_s: 1
Sequence pass/fail:
  Dialog timeout (s): 0
  Interrupt action: No dialog (abort)
  Pass fail action: No dialog (abort)
  Retries: 0
UAInterface: null
User Accounts:
  Administrator: PMI_Admin
  Engineer: Engineer
  Operator: Operator
VIX_Motors:
  axes:
  - X
  - R
  calibrate_ray:
  - 143.5
  - 143.5
  encoder_installed_ray:
  - true
  - false
  encoder_resolution_ray:
  - 4000
  - 1000
  increment_ray:
  - 360
  - 360
  movement_mode: Distance
  on_by_default: true
  port: COM7
  reverse_ray:
  - false
  - false
  enable_homing_ray:
    - false
    - false
  homing_offset_ray: #Difference between motor's home position and the desired home position (defined by wtf_position_parameters)
    - false
    - false
  rotational_ray:
  - false
  - true
  speeds_ray:
  - 100
  - 100
  time_limit_s: 2
  timeout_s: 0.1
TempMon:
  DeviceName: "TankTemp"
  TCoupleType: "J"
WTF_DIO:
  DAQ Device name: WTF4
  Fill/Drain mode: Automatic
  Water level timeout (s): 230
WTF_Interface_Board:
  on_by_default: false
  port: COM2
  timeout_s: 1
WTF_PositionParameters:
  CentreHomeTheta?: true
  ThetaHomeCoord: -90
  ThetaLoadEnc?: false
  ThetaPreHomeMove: 2
  X-Element pitch (mm): 5
  X-Element1: 0
  X-TankInsertionPoint: 108
  XHomeCoord: 263
Software_Version:
  '1.0'
