Analysis:
  capture_rms_only: false
  max_standard_deviation_w: 0.02
  samples_to_remove_at_end: 3
  settling_time_s: 2
Daq_Power_Relay:
  on_by_default: true
  port: COM3
  timeout_s: 1
Debugging:
  disable_password_prompt: false
  end_script_on_errors: false
  oscilloscope_realtime_capture: false
  print_detailed_verbose: false
  sensor_refresh_interval_s: 0.5
  simulate_awg: false
  simulate_balance: false
  simulate_io_board: false
  simulate_motors: false
  simulate_oscilloscope: false
  simulate_power_meters: false
  simulate_sensors: false
  simulate_thermocouple: false
  simulate_ua_error: false
  simulate_ua_interface: false
  simulate_ua_pump_on: true
Forward_Power_Meter:
  cal_fact: 1.0
  serial_number: '11506210019'
FrequencyParameters:
  HF:
    HF.Amplitude(mVpp): 50.0
    HF.BurstCount: 65
    HighFreqLimit(MHz): 13.8
    LowFreqLimit(MHz): 12.8
  LF:
    Amplitude(mVpp): 50.0
    BurstCount: 50
    HighFreqLimit(MHz): 4.8
    LowFreqLimit(MHz): 4.0
  Search:
    CoarseIncr(MHz): 0.1
    FineIncr(MHz): 0.01
Galil_Motors:
  HomeXWithLimit: false
  axes:
  - X
  - R
  calibrate_ray:
  - 12765.95
  - 71.09
  enable_homing_ray:
  - true
  - true
  encoder_installed_ray:
  - false
  - true
  encoder_resolution_ray:
  - 4000
  - 1000
  gearing_ray:
  - 1
  - 1.92
  increment_ray:
  - 5
  - 5
  ip_address: 192.168.42.100
  jog_speed: 1
  move_timeout_s: 300
  movement_mode: Distance
  on_by_default: true
  port: com7
  reverse_ray:
  - false
  - false
  rotational_ray:
  - false
  - true
  scan_speed: 1
  speeds_ray:
  - 9.0
  - 9.0
  time_limit_s: 2
  timeout_s: 0.1
  reverse_theta_home_direction: true
Keysight_AWG:
  amplitude_V: 0.2
  burst_cycles: 4000
  burst_on: true
  burst_period_s: 0.1
  frequency_Hz: 4290000
  identifier: '0x2507'
  offset_V: 0
  output_Impedance: 50
  set_on_startup: true
  trig_in: false
  trig_out: true
Keysight_Oscilloscope:
  autorange_v_startup: false
  averages: 1
  channel: 1
  cycles: 10
  delay_cycles: 0
  ext_trigger: true
  identifier: '0x179B'
  range_mV: 300
  retries: 5
  set_on_startup: true
  timeout_s: 1
MT_Balance:
  port: COM4
  timeout_s: 10
Oscilloscope_timebase:
  Horizontal scale (us): 0.2
  Time offset (us): 29
Paths:
  UA Serial numbers file: \UA serial number and frequency data.txt
  UA results root directory: C:\Users\Public\UA results
Reflected_Power_Meter:
  cal_fact: 1
  serial_number: '11408040323'
Sequence pass/fail:
  Dialog timeout (s): 0
  Interrupt action: Prompt for retry
  Pass fail action: Prompt for retry
  Retries: 5
Software_Version: '1.0'
TempMon:
  DeviceName: TankTemp
  TCoupleType: J
Test_Settings:
  Above_Level_Acceptable: true
  abort_on_fail: false
  check_for_failure_realtime: false
  drain_before_retract: true
UAInterface:
  timeout_s: 2.0
User Accounts:
  Administrator: PMI_Admin
  Engineer: Engineer
  Operator: Operator
VIX_Motors:
  axes:
  - X
  - R
  calibrate_ray:
  - 30.0
  - 15.0
  enable_homing_ray:
  - true
  - true
  encoder_installed_ray:
  - false
  - true
  encoder_resolution_ray:
  - 4000
  - 1000
  gearing_ray:
  - 1
  - 1.92
  increment_ray:
  - 5
  - 2
  move_timeout_s: 300
  movement_mode: Distance
  on_by_default: true
  port: COM7
  reverse_ray:
  - false
  - false
  rotational_ray:
  - false
  - true
  speeds_ray:
  - 5.0
  - 5.0
  time_limit_s: 2
  timeout_s: 0.1
WTF_DIO:
  DAQ Device name: WTF4
  Deactivate_channels_on_startup: false
  Fill/Drain mode: Automatic
  Water level timeout (s): 230
WTF_PositionParameters:
  CentreHomeTheta?: true
  ThetaHomeCoord: -90
  ThetaHomeEdgeCoord: -97
  ThetaHydrophoneCoord: -180
  ThetaLoadEnc?: false
  ThetaPreHomeMove: -90
  X-Element pitch (mm): 5
  X-Element1: 0
  X-TankInsertionPoint: 0
  XHomeCoord: -308.5
  XNegativeLimitMove: 30
