Dummy_Motors:
  axes: ['X','R']
  #steps/mm, float
  calibrate_ray: [1,1]
  #boolean
  reverse_ray: [False,False]
  #mm/s, float
  jog_speed: 1
  scan_speed: 1

VIX_Motors:
  axes: ['X', 'R']
  #steps/mm, float
  calibrate_ray: [1,1]
  #boolean
  reverse_ray: [False, False]
  #mm/s, float
  jog_speed: 1
  scan_speed: 1
  timeout_s: .2
  on_by_default: True
  port: "COM7"

Dummy_Oscilloscope:
  range_mv: 10
  channel: 1
  averages: 16
  capture_period_ns: 5
  cycles: 10
  delay_cycles: 0

Keysight_AWG:
  identifier: "0x2507"
  #Substring that the code checks for in pyvisa resource name to identify the AWG
  frequency_Hz: 4290000
  amplitude_V: .2
  burst: False
  burst_cycles: 50
  ext_trig: False
  burst_period_s: .10
  offset_V: 0
  output: True
  output_Impedance: 50
  set_on_startup: True

Water_Level_Sensor:

Keysight_Oscilloscope:
  identifier: "0x179B"
  #Substring that the code checks for in pyvisa resource name to identify the scope
  range_mv: 10
  channel: 1
  averages: 16
  capture_period_ns: 100
  cycles: 10
  delay_cycles: 0

Pump:
  timeout_s: 1
  on_by_default: False
  port: "COM7"

WTF_Interface_Board:
  timeout_s: 1
  on_by_default: False
  port: "COM6"

MT_Balance:
  timeout_s: 30
  port: "COM7"

Debugging:
  simulate_hw: True

User Accounts:
  Operator: "Operator"
  Engineer: "Engineer"
  Administrator: "PMI_Admin"

WTF_PositionParameters:
  XHomeCoord: 263
  ThetaHomeCoord: -90
  X-TankInsertionPoint: 108
  X-Element1: 0
  X-Element pitch (mm): 5
  ThetaPreHomeMove: 2
  ThetaLoadEnc?: False
  CentreHomeTheta?: True

FrequencyParameters:
  LF:
    LowFreqLimit(MHz): 4
    HighFreqLimit(MHz): 4.8
    Amplitude(mVpp): 50
    BurstCount: 50
  HF:
    LowFreqLimit(MHz): 12.8
    HighFreqLimit(MHz): 13.8
    HF.Amplitude(mVpp): 50
    HF.BurstCount: 65
  Search:
    CoarseIncr(MHz):
      0.1
    FineIncr(MHz):
      0.01

Sequence pass/fail:
  Retries: 0
  Pass fail action: "No dialog (abort)"
  Interrupt action: "No dialog (abort)"
  Dialog timeout (s): 0

WTF_DIO:
  DAQ Device name: "WTF3"
  Water level timeout (s): 230
  Fill/Drain mode: "Automatic"

Autoset timebase:
  Min time of flight (us): 42
  Max time of flight (us): 50

Paths:
  UA results root directory: "C:\\Users\\Isaiah\\OneDrive\\Documents\\UA results"
  UA Serial numbers file: "C:\\Users\\Isaiah\\OneDrive\\Documents\\UA Serial Numbers\\Serial numbers.txt"
