Analysis:
  capture_rms_only: false
  max_standard_deviation_w: 0.1
  samples_to_remove_at_end: 3
  settling_time_s: 0.001
Oscilloscope_timebase:
  Horizontal scale (us): .2     # Default should be .2 us for low frequency and .1 us for high frequency
  Time offset (us): 43           # 43 us for low frequency and 34.75 us for high frequency (depending on hydrophone)
Daq_Power_Relay:
  on_by_default: true
  port: COM3
  timeout_s: 1
Debugging:
  disable_password_prompt: true
  end_script_on_errors: false
  oscilloscope_realtime_capture: false
  simulate_awg: true
  simulate_balance: true
  simulate_balance_error: false
  simulate_io_board: true
  simulate_motor_error: false
  simulate_motors: true
  simulate_oscilloscope: true
  simulate_oscilloscope_error: false
  simulate_ua_pump_on: true
  simulate_power_meters: true
  simulate_sensors: true
  simulate_thermocouple: true
  simulate_thermocouple_error: false
  simulate_ua_error: false
  simulate_ua_interface: true
  drain_before_retract: true
  #Optimal setting if oscilloscope_realtime_capture is False: .5s
  #Optimal setting if oscilloscope_realtime_capture is True: 1.5s
  sensor_refresh_interval_s: .5
Forward_Power_Meter:
  serial_number: '11408040323'
FrequencyParameters:
  HF:
    HF.Amplitude(mVpp): 50.0
    HF.BurstCount: 65
    HighFreqLimit(MHz): 13.8
    LowFreqLimit(MHz): 12.8
  LF:
    Amplitude(mVpp): 50.0
    BurstCount: 50
    HighFreqLimit(MHz): 4.8
    LowFreqLimit(MHz): 4.0
  Search:
    CoarseIncr(MHz): 0.1
    FineIncr(MHz): 0.01
Galil_Motors:
  axes:
    - X
    - R
  calibrate_ray:
    - 1000
    - 11.111111111 #4000/360
  enable_homing_ray:
    - true
    - true
  encoder_installed_ray:
    - false
    - true
  encoder_resolution_ray:
    - 1000
    - 4000
  gearing_ray:
    - 1
    - 1.92
  increment_ray:
    - 5
    - 2
  ip_address: 192.168.42.100
  move_timeout_s: 300
  movement_mode: Distance
  on_by_default: true
  port: COM7
  reverse_ray:
    - false
    - false
  rotational_ray:
    - false
    - true
  speeds_ray:
    - 5 #mm/s
    - 5 #deg/s
  time_limit_s: 2
  timeout_s: 0.1
Keysight_AWG:
  amplitude_V: 0.2
  burst_cycles: 4000
  burst_on: true
  burst_period_s: 0.1
  frequency_Hz: 4290000
  identifier: '0x2507'
  offset_V: 0
  output_Impedance: 50
  set_on_startup: true
  trig_in: false
  trig_out: true
Keysight_Oscilloscope:
  autorange_v_startup: false
  averages: 1
  channel: 1
  cycles: 10
  delay_cycles: 0
  ext_trigger: true
  identifier: '0x179B'
  range_mV: 6000
  retries: 5
  set_on_startup: true
  timeout_s: 1
MT_Balance:
  port: COM4
  timeout_s: 10
Paths:
  Script log directory: C:\Users\Isaiah\Documents\UA results\Logs
  UA Serial numbers file: \Program_Data\UA serial number and frequency data.txt
  UA results root directory: C:\Users\Isaiah\Documents\UA results
Reflected_Power_Meter:
  serial_number: '11506210019'
Sequence pass/fail:
  Dialog timeout (s): 0
  Interrupt action: Prompt for retry #No dialog (abort), Prompt for retry, Retry automatically
  Pass fail action: Prompt for retry #No dialog (abort), Prompt for retry, Retry automatically
  Retries: 0
Software_Version: '1.0'
TempMon:
  DeviceName: TankTemp
  TCoupleType: J
UAInterface:
  timeout_s: 2.0
User Accounts:
  Administrator: PMI_Admin
  Engineer: Engineer
  Operator: Operator
VIX_Motors:
  axes:
    - X
    - R
  calibrate_ray:
    - 30.0
    - 15.0
  enable_homing_ray:
    - true
    - true
  encoder_installed_ray:
    - false
    - true
  encoder_resolution_ray:
    - 4000
    - 1000
  gearing_ray:
    - 1
    - 1.92
  increment_ray:
    - 5
    - 2
  move_timeout_s: 300
  movement_mode: Distance
  on_by_default: true
  port: COM7
  reverse_ray:
    - false
    - false
  rotational_ray:
    - false
    - true
  speeds_ray:
    - 5.0
    - 5.0
  time_limit_s: 2
  timeout_s: 0.1
WTF_DIO:
  DAQ Device name: WTF4
  Fill/Drain mode: Automatic
  Water level timeout (s): 230
WTF_Interface_Board:
  on_by_default: false
  port: COM2
  timeout_s: 1
WTF_PositionParameters:
  CentreHomeTheta?: true
  ThetaHomeCoord: -90
  ThetaHydrophoneCoord: -180
  ThetaLoadEnc?: false
  ThetaPreHomeMove: 2
  X-Element pitch (mm): 5
  X-Element1: 0
  X-TankInsertionPoint: 108
  XHomeCoord: 263
