Debugging:
  simulate_awg: true #Note: this setting also adds simulated values to the balance and power meter readings
  simulate_balance: true
  simulate_io_board: true
  simulate_motors: true
  simulate_oscilloscope: true
  simulate_power_meters: true
  simulate_sensors: true
  simulate_thermocouple: true
  simulate_ua_interface: true
  simulate_ua_pump_on: true