Analysis:
  capture_rms_only: false
  max_standard_deviation_w: 0.02
  samples_to_remove_at_end: 3
  settling_time_s: 2
Oscilloscope_timebase:
  # Default should be .2 us for low frequency and .1 us for high frequency
  Horizontal scale (us): .2
  # 29 us for low frequency and 34.75 us for high frequency (depending on hydrophone)
  Time offset (us): 29
Daq_Power_Relay:
  on_by_default: true
  port: COM3
  timeout_s: 1
Debugging:
  disable_password_prompt: false
  end_script_on_errors: false
  oscilloscope_realtime_capture: false
  print_detailed_verbose: false
  sensor_refresh_interval_s: 0.5
  simulate_awg: false #Note: this setting also adds simulated values to the balance and power meter readings
  simulate_balance: false
  simulate_balance_error: false
  simulate_io_board: false
  simulate_motor_error: false
  simulate_motors: false
  simulate_oscilloscope: false
  simulate_oscilloscope_error: false
  simulate_power_meters: false
  simulate_sensors: false
  simulate_thermocouple: false
  simulate_thermocouple_error: false
  simulate_ua_error: true
  simulate_ua_interface: false
  #Optimal setting if oscilloscope_realtime_capture is False: .5s
  #Optimal setting if oscilloscope_realtime_capture is True: 1.5s
  simulate_ua_pump_on: true
Test_Settings:
  Above_Level_Acceptable: true
  abort_on_fail: false
  drain_before_retract: true
Forward_Power_Meter:
  serial_number: '11506210019'
  cal_fact: 1.1271137
FrequencyParameters:
  HF:
    HF.Amplitude(mVpp): 50.0
    HF.BurstCount: 65
    HighFreqLimit(MHz): 13.8
    LowFreqLimit(MHz): 12.8
  LF:
    Amplitude(mVpp): 50.0
    BurstCount: 50
    HighFreqLimit(MHz): 4.8
    LowFreqLimit(MHz): 4.0
  Search:
    CoarseIncr(MHz): 0.1
    FineIncr(MHz): 0.01
Galil_Motors:
  axes:
    - X
    - R
  calibrate_ray:
    - 12765.95
    - 71.09
  enable_homing_ray:
    - true
    - true
  encoder_installed_ray:
    - false
    - true
  encoder_resolution_ray:
    - 4000
    - 1000
  gearing_ray:
    - 1
    - 1.92
  increment_ray:
    - 5
    - 5
  ip_address: 192.168.42.100
  jog_speed: 1
  move_timeout_s: 300
  movement_mode: Distance
  on_by_default: true
  port: COM7
  reverse_ray:
    - false
    - false
  rotational_ray:
    - false
    - true
  scan_speed: 1
  speeds_ray:
    - 9.0
    - 99.0
  time_limit_s: 2
  timeout_s: 0.1
  HomeXWithLimit: False
Keysight_AWG:
  amplitude_V: 0.2
  burst_cycles: 4000
  burst_on: true
  burst_period_s: 0.1
  frequency_Hz: 4290000
  identifier: '0x2507'
  offset_V: 0
  output_Impedance: 50
  set_on_startup: true
  trig_in: false
  trig_out: true
Keysight_Oscilloscope:
  autorange_v_startup: false
  averages: 1
  channel: 1
  cycles: 10
  delay_cycles: 0
  ext_trigger: true
  identifier: '0x179B'
  range_mV: 300
  retries: 5 #Zero for unlimited retries
  set_on_startup: true
  timeout_s: 1
MT_Balance:
  port: COM4
  timeout_s: 10
Paths:
  #Note: if a drive letter and colon is not provided the program will append the path to the repository path
  UA Serial numbers file: \Program_Data\UA serial number and frequency data.txt
  UA results root directory: C:\Users\Public\UA results
Reflected_Power_Meter:
  serial_number: '11408040323'
  cal_fact: 1.1271137
Sequence pass/fail:
  Dialog timeout (s): 0
  Interrupt action: Retry automatically #No dialog (abort), Prompt for retry, Retry automatically
  Pass fail action: Retry automatically #No dialog (abort), Prompt for retry, Retry automatically
  Retries: 5 #Zero for unlimited retries
Software_Version: '1.0'
TempMon:
  DeviceName: TankTemp
  TCoupleType: J
UAInterface:
  timeout_s: 2.0
User Accounts:
  Administrator: PMI_Admin
  Engineer: Engineer
  Operator: Operator
VIX_Motors:
  axes:
    - X
    - R
  calibrate_ray:
    - 30.0
    - 15.0
  enable_homing_ray:
    - true
    - true
  encoder_installed_ray:
    - false
    - true
  encoder_resolution_ray:
    - 4000
    - 1000
  gearing_ray:
    - 1
    - 1.92
  increment_ray:
    - 5
    - 2
  move_timeout_s: 300
  movement_mode: Distance
  on_by_default: true
  port: COM7
  reverse_ray:
    - false
    - false
  rotational_ray:
    - false
    - true
  speeds_ray:
    - 5.0
    - 5.0
  time_limit_s: 2
  timeout_s: 0.1
WTF_DIO:
  DAQ Device name: WTF4
  Deactivate_channels_on_startup: false
  Fill/Drain mode: Automatic
  Water level timeout (s): 230
WTF_PositionParameters:
  CentreHomeTheta?: true
  ThetaHomeCoord: -90
  ThetaHomeEdgeCoord: -97
  ThetaHydrophoneCoord: -180
  ThetaLoadEnc?: false
  ThetaPreHomeMove: -90
  X-Element pitch (mm): 5
  X-Element1: 0
  X-TankInsertionPoint: 0
  XHomeCoord: -308.5
  XNegativeLimitMove: 30