# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'application_configurations.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1158, 678)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 221, 541))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.widget = SystemStatusIndicator(Dialog)
        self.widget.setGeometry(QtCore.QRect(220, 0, 921, 611))
        self.widget.setObjectName("widget")
        self.apply_all_check = QtWidgets.QCheckBox(Dialog)
        self.apply_all_check.setGeometry(QtCore.QRect(1040, 620, 64, 17))
        self.apply_all_check.setObjectName("apply_all_check")
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(880, 640, 239, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_button = QtWidgets.QPushButton(self.widget1)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(self.widget1)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.apply_button = QtWidgets.QPushButton(self.widget1)
        self.apply_button.setObjectName("apply_button")
        self.horizontalLayout.addWidget(self.apply_button)
        self.widget2 = QtWidgets.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(0, 650, 221, 25))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(26)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.restore_to_button = QtWidgets.QPushButton(self.widget2)
        self.restore_to_button.setObjectName("restore_to_button")
        self.horizontalLayout_2.addWidget(self.restore_to_button)
        self.save_as_button = QtWidgets.QPushButton(self.widget2)
        self.save_as_button.setObjectName("save_as_button")
        self.horizontalLayout_2.addWidget(self.save_as_button)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "System status indicator"))
        item = self.listWidget.item(1)
        item.setText(_translate("Dialog", "Patlite Sounder"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.apply_all_check.setText(_translate("Dialog", "Apply All"))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.apply_button.setText(_translate("Dialog", "Apply"))
        self.restore_to_button.setText(_translate("Dialog", "Restore To..."))
        self.save_as_button.setText(_translate("Dialog", "Save as..."))
from ui_elements.ui_system_status_indicator import SystemStatusIndicator


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
