# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_data_capture.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_test_data_capture(object):
    def setupUi(self, test_data_capture):
        test_data_capture.setObjectName("test_data_capture")
        test_data_capture.resize(407, 290)
        test_data_capture.setMinimumSize(QtCore.QSize(407, 290))
        test_data_capture.setMaximumSize(QtCore.QSize(407, 290))
        test_data_capture.setInputMethodHints(QtCore.Qt.ImhNone)
        self.layoutWidget = QtWidgets.QWidget(test_data_capture)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 60, 135, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.ua_serial_number_vert = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.ua_serial_number_vert.setContentsMargins(0, 0, 0, 0)
        self.ua_serial_number_vert.setObjectName("ua_serial_number_vert")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.ua_serial_number_vert.addWidget(self.label_3)
        self.ua_serial_no_inputline = QtWidgets.QLineEdit(self.layoutWidget)
        self.ua_serial_no_inputline.setText("")
        self.ua_serial_no_inputline.setObjectName("ua_serial_no_inputline")
        self.ua_serial_number_vert.addWidget(self.ua_serial_no_inputline)
        self.layoutWidget1 = QtWidgets.QWidget(test_data_capture)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 110, 330, 130))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.comment_vert = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.comment_vert.setContentsMargins(0, 0, 0, 0)
        self.comment_vert.setObjectName("comment_vert")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.comment_vert.addWidget(self.label_4)
        self.comment_inputbox = QtWidgets.QTextEdit(self.layoutWidget1)
        self.comment_inputbox.setObjectName("comment_inputbox")
        self.comment_vert.addWidget(self.comment_inputbox)
        self.label_2 = QtWidgets.QLabel(test_data_capture)
        self.label_2.setGeometry(QtCore.QRect(212, 12, 23, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(test_data_capture)
        self.label.setGeometry(QtCore.QRect(32, 12, 66, 16))
        self.label.setObjectName("label")
        self.test_operator_inputline = QtWidgets.QLineEdit(test_data_capture)
        self.test_operator_inputline.setGeometry(QtCore.QRect(32, 31, 131, 20))
        self.test_operator_inputline.setText("")
        self.test_operator_inputline.setObjectName("test_operator_inputline")
        self.ok_button = QtWidgets.QPushButton(test_data_capture)
        self.ok_button.setGeometry(QtCore.QRect(190, 260, 75, 23))
        self.ok_button.setObjectName("ok_button")
        self.cancel_button = QtWidgets.QPushButton(test_data_capture)
        self.cancel_button.setGeometry(QtCore.QRect(280, 260, 75, 23))
        self.cancel_button.setObjectName("cancel_button")
        self.date_output = QtWidgets.QTextBrowser(test_data_capture)
        self.date_output.setGeometry(QtCore.QRect(210, 30, 151, 31))
        self.date_output.setAcceptDrops(False)
        self.date_output.setInputMethodHints(QtCore.Qt.ImhNone)
        self.date_output.setObjectName("date_output")

        self.retranslateUi(test_data_capture)
        QtCore.QMetaObject.connectSlotsByName(test_data_capture)

    def retranslateUi(self, test_data_capture):
        _translate = QtCore.QCoreApplication.translate
        test_data_capture.setWindowTitle(_translate("test_data_capture", "Dialog"))
        self.label_3.setText(_translate("test_data_capture", "UA serial number"))
        self.label_4.setText(_translate("test_data_capture", "Comment (optional)"))
        self.label_2.setText(_translate("test_data_capture", "Date"))
        self.label.setText(_translate("test_data_capture", "Test operator"))
        self.ok_button.setText(_translate("test_data_capture", "Ok"))
        self.cancel_button.setText(_translate("test_data_capture", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    test_data_capture = QtWidgets.QDialog()
    ui = Ui_test_data_capture()
    ui.setupUi(test_data_capture)
    test_data_capture.show()
    sys.exit(app.exec_())
