# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test_data_capture.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_test_data_capture(object):
    def setupUi(self, test_data_capture):
        test_data_capture.setObjectName("test_data_capture")
        test_data_capture.resize(400, 284)
        self.ok_cancel_button_box = QtWidgets.QDialogButtonBox(test_data_capture)
        self.ok_cancel_button_box.setGeometry(QtCore.QRect(250, 250, 121, 32))
        self.ok_cancel_button_box.setOrientation(QtCore.Qt.Horizontal)
        self.ok_cancel_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ok_cancel_button_box.setObjectName("ok_cancel_button_box")
        self.widget = QtWidgets.QWidget(test_data_capture)
        self.widget.setGeometry(QtCore.QRect(30, 60, 135, 41))
        self.widget.setObjectName("widget")
        self.ua_serial_number_vert = QtWidgets.QVBoxLayout(self.widget)
        self.ua_serial_number_vert.setContentsMargins(0, 0, 0, 0)
        self.ua_serial_number_vert.setObjectName("ua_serial_number_vert")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.ua_serial_number_vert.addWidget(self.label_3)
        self.ua_serial_no_inputline = QtWidgets.QLineEdit(self.widget)
        self.ua_serial_no_inputline.setText("")
        self.ua_serial_no_inputline.setObjectName("ua_serial_no_inputline")
        self.ua_serial_number_vert.addWidget(self.ua_serial_no_inputline)
        self.widget1 = QtWidgets.QWidget(test_data_capture)
        self.widget1.setGeometry(QtCore.QRect(30, 110, 330, 130))
        self.widget1.setObjectName("widget1")
        self.comment_vert = QtWidgets.QVBoxLayout(self.widget1)
        self.comment_vert.setContentsMargins(0, 0, 0, 0)
        self.comment_vert.setObjectName("comment_vert")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.comment_vert.addWidget(self.label_4)
        self.comment_inputbox = QtWidgets.QTextEdit(self.widget1)
        self.comment_inputbox.setObjectName("comment_inputbox")
        self.comment_vert.addWidget(self.comment_inputbox)
        self.widget2 = QtWidgets.QWidget(test_data_capture)
        self.widget2.setGeometry(QtCore.QRect(30, 10, 331, 43))
        self.widget2.setObjectName("widget2")
        self.test_operator_upper_horz = QtWidgets.QHBoxLayout(self.widget2)
        self.test_operator_upper_horz.setContentsMargins(0, 0, 0, 0)
        self.test_operator_upper_horz.setSpacing(45)
        self.test_operator_upper_horz.setObjectName("test_operator_upper_horz")
        self.test_operator_vert = QtWidgets.QVBoxLayout()
        self.test_operator_vert.setObjectName("test_operator_vert")
        self.label = QtWidgets.QLabel(self.widget2)
        self.label.setObjectName("label")
        self.test_operator_vert.addWidget(self.label)
        self.test_operator_inputline = QtWidgets.QLineEdit(self.widget2)
        self.test_operator_inputline.setText("")
        self.test_operator_inputline.setObjectName("test_operator_inputline")
        self.test_operator_vert.addWidget(self.test_operator_inputline)
        self.test_operator_upper_horz.addLayout(self.test_operator_vert)
        self.date_vert = QtWidgets.QVBoxLayout()
        self.date_vert.setObjectName("date_vert")
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setObjectName("label_2")
        self.date_vert.addWidget(self.label_2)
        self.date_inputline = QtWidgets.QLineEdit(self.widget2)
        self.date_inputline.setText("")
        self.date_inputline.setObjectName("date_inputline")
        self.date_vert.addWidget(self.date_inputline)
        self.test_operator_upper_horz.addLayout(self.date_vert)

        self.retranslateUi(test_data_capture)
        self.ok_cancel_button_box.accepted.connect(test_data_capture.accept) # type: ignore
        self.ok_cancel_button_box.rejected.connect(test_data_capture.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(test_data_capture)

    def retranslateUi(self, test_data_capture):
        _translate = QtCore.QCoreApplication.translate
        test_data_capture.setWindowTitle(_translate("test_data_capture", "Dialog"))
        self.label_3.setText(_translate("test_data_capture", "UA serial number"))
        self.label_4.setText(_translate("test_data_capture", "Comment (optional)"))
        self.label.setText(_translate("test_data_capture", "Test operator"))
        self.label_2.setText(_translate("test_data_capture", "Date"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    test_data_capture = QtWidgets.QDialog()
    ui = Ui_test_data_capture()
    ui.setupUi(test_data_capture)
    test_data_capture.show()
    sys.exit(app.exec_())
