# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_oscilloscope_channels.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_config_osc_channels(object):
    def setupUi(self, config_osc_channels):
        config_osc_channels.setObjectName("config_osc_channels")
        config_osc_channels.resize(602, 459)
        self.label = QtWidgets.QLabel(config_osc_channels)
        self.label.setGeometry(QtCore.QRect(30, 40, 80, 13))
        self.label.setObjectName("label")
        self.channel_set_frame = QtWidgets.QFrame(config_osc_channels)
        self.channel_set_frame.setGeometry(QtCore.QRect(30, 60, 221, 161))
        self.channel_set_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.channel_set_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.channel_set_frame.setObjectName("channel_set_frame")
        self.layoutWidget = QtWidgets.QWidget(self.channel_set_frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, -1, 221, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.channel_set_horz = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.channel_set_horz.setContentsMargins(0, 0, 0, 0)
        self.channel_set_horz.setSpacing(0)
        self.channel_set_horz.setObjectName("channel_set_horz")
        self.channel_frame_left = QtWidgets.QFrame(self.layoutWidget)
        self.channel_frame_left.setFrameShape(QtWidgets.QFrame.Box)
        self.channel_frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.channel_frame_left.setObjectName("channel_frame_left")
        self.layoutWidget1 = QtWidgets.QWidget(self.channel_frame_left)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 90, 140))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.channel_gain_offset_vert = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.channel_gain_offset_vert.setContentsMargins(0, 0, 0, 0)
        self.channel_gain_offset_vert.setObjectName("channel_gain_offset_vert")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.channel_gain_offset_vert.addWidget(self.label_2)
        self.channel_combo = QtWidgets.QComboBox(self.layoutWidget1)
        self.channel_combo.setObjectName("channel_combo")
        self.channel_combo.addItem("")
        self.channel_combo.addItem("")
        self.channel_gain_offset_vert.addWidget(self.channel_combo)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.channel_gain_offset_vert.addWidget(self.label_4)
        self.gain_spin = QtWidgets.QSpinBox(self.layoutWidget1)
        self.gain_spin.setObjectName("gain_spin")
        self.channel_gain_offset_vert.addWidget(self.gain_spin)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.channel_gain_offset_vert.addWidget(self.label_5)
        self.offset_spin = QtWidgets.QSpinBox(self.layoutWidget1)
        self.offset_spin.setObjectName("offset_spin")
        self.channel_gain_offset_vert.addWidget(self.offset_spin)
        self.channel_set_horz.addWidget(self.channel_frame_left)
        self.channel_right_right = QtWidgets.QFrame(self.layoutWidget)
        self.channel_right_right.setStyleSheet("background:lightgrey")
        self.channel_right_right.setFrameShape(QtWidgets.QFrame.Box)
        self.channel_right_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.channel_right_right.setObjectName("channel_right_right")
        self.layoutWidget2 = QtWidgets.QWidget(self.channel_right_right)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 90, 140))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.channel_gain_offset_right_vert = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.channel_gain_offset_right_vert.setContentsMargins(0, 0, 0, 0)
        self.channel_gain_offset_right_vert.setObjectName("channel_gain_offset_right_vert")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.channel_gain_offset_right_vert.addWidget(self.label_3)
        self.channel_right_combo = QtWidgets.QComboBox(self.layoutWidget2)
        self.channel_right_combo.setEnabled(False)
        self.channel_right_combo.setObjectName("channel_right_combo")
        self.channel_right_combo.addItem("")
        self.channel_right_combo.addItem("")
        self.channel_gain_offset_right_vert.addWidget(self.channel_right_combo)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.channel_gain_offset_right_vert.addWidget(self.label_6)
        self.gain_right_spin = QtWidgets.QSpinBox(self.layoutWidget2)
        self.gain_right_spin.setEnabled(False)
        self.gain_right_spin.setObjectName("gain_right_spin")
        self.channel_gain_offset_right_vert.addWidget(self.gain_right_spin)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.channel_gain_offset_right_vert.addWidget(self.label_7)
        self.offset_right_spin = QtWidgets.QSpinBox(self.layoutWidget2)
        self.offset_right_spin.setEnabled(False)
        self.offset_right_spin.setObjectName("offset_right_spin")
        self.channel_gain_offset_right_vert.addWidget(self.offset_right_spin)
        self.channel_set_horz.addWidget(self.channel_right_right)
        self.config_osc_channel_note = QtWidgets.QTextBrowser(config_osc_channels)
        self.config_osc_channel_note.setGeometry(QtCore.QRect(270, 60, 251, 191))
        self.config_osc_channel_note.setStyleSheet("background-color:lightyellow")
        self.config_osc_channel_note.setFrameShape(QtWidgets.QFrame.Box)
        self.config_osc_channel_note.setObjectName("config_osc_channel_note")

        self.retranslateUi(config_osc_channels)
        QtCore.QMetaObject.connectSlotsByName(config_osc_channels)

    def retranslateUi(self, config_osc_channels):
        _translate = QtCore.QCoreApplication.translate
        config_osc_channels.setWindowTitle(_translate("config_osc_channels", "Form"))
        self.label.setText(_translate("config_osc_channels", "Channel settings"))
        self.label_2.setText(_translate("config_osc_channels", "Channel"))
        self.channel_combo.setItemText(0, _translate("config_osc_channels", "Channel 1"))
        self.channel_combo.setItemText(1, _translate("config_osc_channels", "Channel 2"))
        self.label_4.setText(_translate("config_osc_channels", "Gain (mV/div)"))
        self.label_5.setText(_translate("config_osc_channels", "Offset (mV)"))
        self.label_3.setText(_translate("config_osc_channels", "Channel"))
        self.channel_right_combo.setItemText(0, _translate("config_osc_channels", "Channel 1"))
        self.channel_right_combo.setItemText(1, _translate("config_osc_channels", "Channel 2"))
        self.label_6.setText(_translate("config_osc_channels", "Gain (mV/div)"))
        self.label_7.setText(_translate("config_osc_channels", "Offset (mV)"))
        self.config_osc_channel_note.setHtml(_translate("config_osc_channels", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; text-decoration: underline;\">Note:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">This step can be used to ensure the correct channels</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">are enabled on the oscilloscope and that the gain and</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">offset are at specific values.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">To set both channels simply select the Channel name</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">in the greyed out box to enable it.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    config_osc_channels = QtWidgets.QWidget()
    ui = Ui_config_osc_channels()
    ui.setupUi(config_osc_channels)
    config_osc_channels.show()
    sys.exit(app.exec_())
