# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_ua_calibration.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 407)
        self.read_from_ua_button = QtWidgets.QPushButton(Form)
        self.read_from_ua_button.setGeometry(QtCore.QRect(320, 373, 111, 31))
        self.read_from_ua_button.setObjectName("read_from_ua_button")
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(10, 23, 81, 16))
        self.label_34.setObjectName("label_34")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 43, 411, 325))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tooltip = QtWidgets.QWidget(Form)
        self.tooltip.setGeometry(QtCore.QRect(0, 0, 449, 23))
        self.tooltip.setObjectName("tooltip")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.read_from_ua_button.setText(_translate("Form", "Read from UA"))
        self.label_34.setText(_translate("Form", "Cal Data"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Schema"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "SerialNumber"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "ProductionDate"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "HardwareCode"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "CommonLowFreq"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "CommonHighFreq"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "BeamAlign"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "Command"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "Status"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "FWVersion"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Cal Data Array"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Low Freq"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "High Freq"))
        self.tooltip.setToolTip(_translate("Form", "The table on the left displays the calibration data stored internally in the ultrasound actuator. The table on the right shows the efficiency of each element for both high and low frequency tests"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
