# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_prompt_user_for_action.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(245, 275)
        Form.setMinimumSize(QtCore.QSize(245, 275))
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 230, 260))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 85, 16))
        self.label_8.setObjectName("label_8")
        self.prompt_field = QtWidgets.QComboBox(self.frame)
        self.prompt_field.setGeometry(QtCore.QRect(10, 30, 125, 20))
        self.prompt_field.setObjectName("prompt_field")
        self.prompt_field.addItem("")
        self.prompt_field.addItem("")
        self.prompt_field.addItem("")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label.setObjectName("label")
        self.prompt_message_box = QtWidgets.QTextEdit(self.frame)
        self.prompt_message_box.setEnabled(False)
        self.prompt_message_box.setGeometry(QtCore.QRect(10, 80, 211, 171))
        self.prompt_message_box.setObjectName("prompt_message_box")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Prompt User For Action"))
        self.label_8.setText(_translate("Form", "Select Prompt"))
        self.prompt_field.setItemText(0, _translate("Form", "Disable UA Pump"))
        self.prompt_field.setItemText(1, _translate("Form", "Selection 2"))
        self.prompt_field.setItemText(2, _translate("Form", "Selection 3"))
        self.label.setText(_translate("Form", "Prompt Message"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
