# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtf_user_prompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_test_data_capture(object):
    def setupUi(self, test_data_capture):
        test_data_capture.setObjectName("test_data_capture")
        test_data_capture.resize(499, 280)
        self.user_prompt_output = QtWidgets.QTextBrowser(test_data_capture)
        self.user_prompt_output.setGeometry(QtCore.QRect(10, 10, 481, 191))
        self.user_prompt_output.setFrameShape(QtWidgets.QFrame.Panel)
        self.user_prompt_output.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.user_prompt_output.setLineWidth(2)
        self.user_prompt_output.setObjectName("user_prompt_output")
        self.layoutWidget = QtWidgets.QWidget(test_data_capture)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 230, 261, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.buttons_horz = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.buttons_horz.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.buttons_horz.setContentsMargins(0, 0, 0, 0)
        self.buttons_horz.setSpacing(13)
        self.buttons_horz.setObjectName("buttons_horz")
        self.abort_button = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abort_button.sizePolicy().hasHeightForWidth())
        self.abort_button.setSizePolicy(sizePolicy)
        self.abort_button.setMinimumSize(QtCore.QSize(70, 30))
        self.abort_button.setMaximumSize(QtCore.QSize(70, 30))
        self.abort_button.setObjectName("abort_button")
        self.buttons_horz.addWidget(self.abort_button)
        self.retry_button = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.retry_button.sizePolicy().hasHeightForWidth())
        self.retry_button.setSizePolicy(sizePolicy)
        self.retry_button.setMaximumSize(QtCore.QSize(70, 30))
        self.retry_button.setObjectName("retry_button")
        self.buttons_horz.addWidget(self.retry_button)
        self.continue_button = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continue_button.sizePolicy().hasHeightForWidth())
        self.continue_button.setSizePolicy(sizePolicy)
        self.continue_button.setMinimumSize(QtCore.QSize(70, 30))
        self.continue_button.setMaximumSize(QtCore.QSize(70, 30))
        self.continue_button.setObjectName("continue_button")
        self.buttons_horz.addWidget(self.continue_button)

        self.retranslateUi(test_data_capture)
        QtCore.QMetaObject.connectSlotsByName(test_data_capture)

    def retranslateUi(self, test_data_capture):
        _translate = QtCore.QCoreApplication.translate
        test_data_capture.setWindowTitle(_translate("test_data_capture", "WTF user prompt"))
        self.abort_button.setText(_translate("test_data_capture", "Abort"))
        self.retry_button.setText(_translate("test_data_capture", "Retry"))
        self.continue_button.setText(_translate("test_data_capture", "Continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    test_data_capture = QtWidgets.QDialog()
    ui = Ui_test_data_capture()
    ui.setupUi(test_data_capture)
    test_data_capture.show()
    sys.exit(app.exec_())
