# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtf_user_prompt_pump_not_running.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wtf_user_prompt_pump_not_running(object):
    def setupUi(self, wtf_user_prompt_pump_not_running):
        wtf_user_prompt_pump_not_running.setObjectName("wtf_user_prompt_pump_not_running")
        wtf_user_prompt_pump_not_running.resize(400, 157)
        wtf_user_prompt_pump_not_running.setMinimumSize(QtCore.QSize(400, 157))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        wtf_user_prompt_pump_not_running.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(wtf_user_prompt_pump_not_running)
        self.layoutWidget.setGeometry(QtCore.QRect(180, 100, 211, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.cont_abort_horz = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.cont_abort_horz.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.cont_abort_horz.setContentsMargins(0, 0, 0, 0)
        self.cont_abort_horz.setSpacing(13)
        self.cont_abort_horz.setObjectName("cont_abort_horz")
        self.continue_button = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continue_button.sizePolicy().hasHeightForWidth())
        self.continue_button.setSizePolicy(sizePolicy)
        self.continue_button.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.continue_button.setFont(font)
        self.continue_button.setObjectName("continue_button")
        self.cont_abort_horz.addWidget(self.continue_button)
        self.abort_button = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abort_button.sizePolicy().hasHeightForWidth())
        self.abort_button.setSizePolicy(sizePolicy)
        self.abort_button.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.abort_button.setFont(font)
        self.abort_button.setObjectName("abort_button")
        self.cont_abort_horz.addWidget(self.abort_button)
        self.user_prompt_output = QtWidgets.QTextBrowser(wtf_user_prompt_pump_not_running)
        self.user_prompt_output.setGeometry(QtCore.QRect(10, 10, 381, 71))
        self.user_prompt_output.setFrameShape(QtWidgets.QFrame.Panel)
        self.user_prompt_output.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.user_prompt_output.setLineWidth(2)
        self.user_prompt_output.setObjectName("user_prompt_output")
        self.ua_pump_status = Switch(wtf_user_prompt_pump_not_running)
        self.ua_pump_status.setEnabled(True)
        self.ua_pump_status.setGeometry(QtCore.QRect(10, 120, 71, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 197, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 197, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 197, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 197, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 197, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 197, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 197, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 197, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 197, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.ua_pump_status.setPalette(palette)
        self.ua_pump_status.setAutoFillBackground(False)
        self.ua_pump_status.setStyleSheet("background-color:#00c500")
        self.ua_pump_status.setText("")
        self.ua_pump_status.setObjectName("ua_pump_status")
        self.label = QtWidgets.QLabel(wtf_user_prompt_pump_not_running)
        self.label.setGeometry(QtCore.QRect(10, 100, 76, 13))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(wtf_user_prompt_pump_not_running)
        QtCore.QMetaObject.connectSlotsByName(wtf_user_prompt_pump_not_running)

    def retranslateUi(self, wtf_user_prompt_pump_not_running):
        _translate = QtCore.QCoreApplication.translate
        wtf_user_prompt_pump_not_running.setWindowTitle(_translate("wtf_user_prompt_pump_not_running", "Dialog"))
        self.continue_button.setText(_translate("wtf_user_prompt_pump_not_running", "Continue"))
        self.abort_button.setText(_translate("wtf_user_prompt_pump_not_running", "Abort"))
        self.user_prompt_output.setHtml(_translate("wtf_user_prompt_pump_not_running", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">UA pump not running.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:400;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">Please enable the UA pump and click to continue.</span></p></body></html>"))
        self.label.setText(_translate("wtf_user_prompt_pump_not_running", "UA pump status"))
from ui_elements.switch import Switch


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wtf_user_prompt_pump_not_running = QtWidgets.QDialog()
    ui = Ui_wtf_user_prompt_pump_not_running()
    ui.setupUi(wtf_user_prompt_pump_not_running)
    wtf_user_prompt_pump_not_running.show()
    sys.exit(app.exec_())
